name: "Google Cloud Container Registry"
description: "Push a docker image to Google Cloud Container Registry"

branding:
  icon: "upload-cloud"
  color: "red"

inputs:
  creds:
    description: "Contents of a Service Account JSON Key"
    required: true
  registry:
    description: "Registry host name (must match dst image)" 
    required: false
    default: "gcr.io"
  src:
    description: "Source image name"
    required: true
  dst:
    description: "Destination image name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Push to Google Cloud Container Registry
      shell: bash
      run: |
        docker login -u _json_key -p '${{ inputs.creds }}' 'https://${{ inputs.registry }}' 2>/dev/null
        docker tag '${{ inputs.src }}' '${{ inputs.dst }}'
        docker push '${{ inputs.dst }}'
        echo "Successfully pushed ${{ inputs.src }} to ${{ inputs.dst }}"

